ex1 = [[
    'programa 1', 
    ['nome',
    'Quebrando a cabeça do fox'], 
    ['inputs',
    ['valor mínimo',
    0], 
    ['valor máximo', 
    [99]], 
    ['faixa de idade', 
    [10,
    22]]]],
    ['programa 2',
    ['nome',
    'Tic-tac-toe'], 
    ['inputs',
    ['valor mínimo',
    5], 
    ['valor máximo', 
    [100]], 
    ['faixa de idade', 
    [16,
    30]]]]]
print(f'{ex1[0][1][1]}')